"""
Pydantic models for Module 2.6 — Actionable Insights & Tradeoffs.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, Field


class TradeoffRequest(BaseModel):
    """Request body for POST /api/v1/tradeoffs/compute."""

    current_node_id: UUID
    alternative_node_id: UUID
    org_id: UUID
    disruption_alert_id: UUID


class MetricResult(BaseModel):
    """A single axis of the 4-axis tradeoff comparison."""

    metric_type: Literal["financial", "time", "carbon", "reliability"]
    current_value: float
    alternative_value: float
    delta: float  # alternative_value - current_value
    unit: str
    is_improvement: bool  # True if the alternative is better than current


class TradeoffAnalysisResponse(BaseModel):
    """Full 4-axis tradeoff analysis returned to the Flutter tradeoffs drawer."""

    analysis_id: UUID
    org_id: UUID
    current_node_id: UUID
    alternative_node_id: UUID
    disruption_alert_id: UUID
    metrics: List[MetricResult]  # Exactly 4 items
    overall_recommendation: Literal["switch", "stay", "investigate"]
    recommendation_confidence: float  # 0.0 – 1.0
    created_at: datetime


class RerouteSuggestion(BaseModel):
    """A single rerouting option generated by the InsightsEngine (Module 2.6A)."""

    suggestion_text: str  # e.g. "Reroute via Colombo Port saves ~14h"
    time_saved_hours: float
    carbon_delta_kg: float
    confidence: float
    alternative_node_id: Optional[UUID] = None
